Repository park-junha/GradPlanner, pull requests merged in 2020-02, with the labels that each got.

#107 Minors
  backend/data.sql
  backend/schema.sql
Labels: P5: Priority Not Set, enhancement

#111 fixed foreign key issue in MinorReqs inserts in data.sql
  backend/data.sql
Labels: P1: Crucial, REGRESSION, bug

#108 UI changes
  static/css/index_styles.css
  static/css/schedule_styles.css
  static/css/styles.css
  static/img/feedback.png
  static/img/home-button-img.jpg
  static/img/mail-512.png
  templates/index.html
  templates/main.html
  templates/schedule.html
  templates/selectmajor.html
  templates/selectrequisites.html
Labels: P3: Moderate, enhancement

#113 Removed print statement of major query
  main.py
Labels: P4: Low

#114 Too few classes scheduled a quarter
  backend/data.sql
  backend/schema.sql
  main.py
  templates/schedule.html
  templates/selectrequisites.html
Labels: P2: High, bug

#115 Fixed incorrect scheduling bug - issue #62
  main.py
  templates/main.html
Labels: P1: Crucial, bug
